disabled_rules:
  - function_parameter_count
  - large_tuple
  - identifier_name
opt_in_rules:
  - closure_end_indentation
  - closure_spacing
  - conditional_returns_on_newline
  - contains_over_first_not_nil
  - empty_count
  - explicit_init
  - fatal_error_message
  - force_unwrapping
  - joined_default_parameter
  - let_var_whitespace
  - literal_expression_end_indentation
  - multiline_arguments
  - multiline_parameters
  - nimble_operator
  - number_separator
  - operator_usage_whitespace
  - overridden_super_call
  - pattern_matching_keywords
  - redundant_nil_coalescing
  - single_test_class
  - strict_fileprivate
  - switch_case_on_newline
  - trailing_closure
  - unneeded_parentheses_in_closure_argument
  - vertical_parameter_alignment_on_call
line_length:
  warning: 120
  error: 160
function_body_length:
  warning: 100
  error: 200
file_length:
  warning: 500
  error: 1000
statement_position:
  statement_mode: uncuddled_else
empty_count:
  severity: warning
force_cast:
  severity: warning
force_try:
  severity: warning
function_parameter_count:
  severity: warning
shorthand_operator:
  severity: warning
large_tuple:
  severity: warning
